In [53]:
import pandas as pd

In [54]:
df = pd.read_excel('data/ScrabbleGames.xlsx')

In [55]:
df.head(1)

,gameid,tourneyid,tie,winnerid,winnername,winnerscore,winneroldrating,winnernewrating,winnerpos,loserid,losername,loserscore,loseroldrating,losernewrating,loserpos,round,division,date,lexicon,year
0,451519,1590,0,38,Matt Laufer,0,1892,1877,5,608,Pam Grazette,0,1712,1692,14,1,1,1994-03-11,0,1994

Сгруппируйте датафрейм по переменной tourneyid, затем определите тип взаимосвязи между средними значениями переменных winnerscore и winnernewrating. Выберите один верный ответ.

In [56]:
winnerscore = df.groupby('tourneyid')['winnerscore'].mean()
winnernewrating = df.groupby('tourneyid')['winnernewrating'].mean()

In [57]:
winners = pd.concat([winnerscore, winnernewrating], axis=1)
winners.corr()

                 winnerscore  winnernewrating
winnerscore         1.000000        -0.604013
winnernewrating    -0.604013         1.000000

Укажите, верно ли следующее утверждение: очки, набранные победителем, напрямую и сильно зависят от очков, набранных проигравшим. Сгруппируйте датафрейм по переменной tourneyid и посмотрите на средние значения интересующих нас переменных.

In [58]:
winnerscore = df.groupby('tourneyid')['winnerscore'].mean()
loserscore = df.groupby('tourneyid')['loserscore'].mean()

In [59]:
scores = pd.concat([winnerscore, loserscore], axis=1)
scores.corr()

             winnerscore  loserscore
winnerscore     1.000000    0.999938
loserscore      0.999938    1.000000

Между какими переменными можно найти интерпретируемый коэффициент корреляции? Выберите один верный ответ.

In [60]:
df.corr()

,gameid,tourneyid,tie,winnerid,winnerscore,winneroldrating,winnernewrating,winnerpos,loserid,loserscore,loseroldrating,losernewrating,loserpos,round,division,lexicon,year
gameid,1.000000,0.027739,0.011730,0.226863,-0.076119,-0.565785,-0.623378,0.026757,0.250447,-0.075867,-0.554665,-0.612148,0.031006,0.057056,0.626632,NaN,NaN
tourneyid,0.027739,1.000000,0.001295,0.039115,0.017727,-0.063566,-0.022334,-0.155506,0.052486,0.018043,-0.055418,-0.012234,-0.174694,-0.155245,0.034172,NaN,NaN
tie,0.011730,0.001295,1.000000,-0.018818,-0.002352,0.004529,-0.000327,0.011076,0.012602,-0.001386,0.005514,0.008880,-0.002666,0.003101,-0.006544,NaN,NaN
winnerid,0.226863,0.039115,-0.018818,1.000000,-0.045205,-0.423279,-0.369051,0.026496,0.190702,-0.045269,-0.340001,-0.341927,-0.011044,-0.067125,0.246841,NaN,NaN
winnerscore,-0.076119,0.017727,-0.002352,-0.045205,1.000000,0.095746,0.075334,0.005435,-0.043951,0.985757,0.089424,0.075328,0.011664,0.038221,-0.078595,NaN,NaN
winneroldrating,-0.565785,-0.063566,0.004529,-0.423279,0.095746,1.000000,0.836087,0.016586,-0.352453,0.095344,0.740348,0.775428,0.066683,0.110590,-0.609908,NaN,NaN
winnernewrating,-0.623378,-0.022334,-0.000327,-0.369051,0.075334,0.836087,1.000000,0.014694,-0.359309,0.074872,0.771732,0.892553,0.092622,0.112238,-0.659330,NaN,NaN
winnerpos,0.026757,-0.155506,0.011076,0.026496,0.005435,0.016586,0.014694,1.000000,-0.005181,0.006901,0.048060,0.088034,0.772008,0.322588,-0.159694,NaN,NaN
loserid,0.250447,0.052486,0.012602,0.190702,-0.043951,-0.352453,-0.359309,-0.005181,1.000000,-0.044019,-0.467082,-0.405584,0.025844,-0.091991,0.242270,NaN,NaN
loserscore,-0.075867,0.018043,-0.001386,-0.045269,0.985757,0.095344,0.074872,0.006901,-0.044019,1.000000,0.090858,0.076116,0.010405,0.038564,-0.078566,NaN,NaN
loseroldrating,-0.554665,-0.055418,0.005514,-0.340001,0.089424,0.740348,0.771732,0.048060,-0.467082,0.090858,1.000000,0.858149,0.003083,0.135149,-0.571728,NaN,NaN
losernewrating,-0.612148,-0.012234,0.008880,-0.341927,0.075328,0.775428,0.892553,0.088034,-0.405584,0.076116,0.858149,1.000000,0.028596,0.140889,-0.638442,NaN,NaN
loserpos,0.031006,-0.174694,-0.002666,-0.011044,0.011664,0.066683,0.092622,0.772008,0.025844,0.010405,0.003083,0.028596,1.000000,0.313379,-0.170317,NaN,NaN
round,0.057056,-0.155245,0.003101,-0.067125,0.038221,0.110590,0.112238,0.322588,-0.091991,0.038564,0.135149,0.140889,0.313379,1.000000,-0.077866,NaN,NaN
division,0.626632,0.034172,-0.006544,0.246841,-0.078595,-0.609908,-0.659330,-0.159694,0.242270,-0.078566,-0.571728,-0.638442,-0.170317,-0.077866,1.000000,NaN,NaN
lexicon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Сгруппируйте датафрейм по переменной tourneyid, затем рассчитайте коэффициент корреляции между средними значениями переменных winnernewrating и losernewrating. Введите ответ в виде десятичной дроби, округлите до двух знаков после запятой (например, 0.23); если связь обратная, не забудьте указать минус перед числом.

In [61]:
winnernewrating = df.groupby('tourneyid')['winnernewrating'].mean()
losernewrating = df.groupby('tourneyid')['losernewrating'].mean()
newratings = pd.concat([winnernewrating, losernewrating], axis=1)
newratings.corr()

                 winnernewrating  losernewrating
winnernewrating         1.000000        0.978357
losernewrating          0.978357        1.000000

Выберите только первые раунды турнира, сгруппируйте датафрейм по переменной tourneyid, затем рассчитайте коэффициент корреляции между переменными winnerscore и loserscore. Введите ответ в виде десятичной дроби, до двух знаков после запятой (например, 0.29); если связь обратная, не забудьте указать минус перед числом.

In [62]:
winnerscore = df.groupby('tourneyid')['winnerscore'].mean()
loserscore = df.groupby('tourneyid')['loserscore'].mean()
scores = pd.concat([winnerscore, loserscore], axis=1)
scores.corr()

             winnerscore  loserscore
winnerscore     1.000000    0.999938
loserscore      0.999938    1.000000

Укажите, верно ли следующее утверждение: переменная tie не влияет на характер взаимосвязи между переменными winnernewrating и losernewrating. Сгруппируйте датафрейм по переменной tourneyid, затем рассчитайте коэффициент корреляции между средними значениями указанных переменных.

In [63]:
winnernewrating = df.groupby('tourneyid')['winnernewrating'].mean()
losernewrating = df.groupby('tourneyid')['losernewrating'].mean()
tie = df.groupby('tourneyid')['tie'].mean()
ratings = pd.concat([winnernewrating, losernewrating, tie], axis=1)
ratings.corr()

                 winnernewrating  losernewrating       tie
winnernewrating         1.000000        0.978357  0.167036
losernewrating          0.978357        1.000000  0.162001
tie                     0.167036        0.162001  1.000000

Выберите самого часто встречающегося победителя (столбец winnername). Сгруппируйте датафрейм по переменной tourneyid, затем рассчитайте коэффициент корреляции между средними значениями переменных winnerscore и winneroldrating. Введите ответ в виде десятичной дроби, округлите до двух знаков после запятой; если связь обратная, не забудьте указать минус перед числом.

In [64]:
df['winnername'].mode()

0    Lester Schonbrun
dtype: object

In [65]:
winnerscore = df[df['winnername'] == 'Lester Schonbrun'].groupby('tourneyid')['winnerscore'].mean()
winneroldrating = df[df['winnername'] == 'Lester Schonbrun'].groupby('tourneyid')['winneroldrating'].mean()
dLesterSchonbrun = pd.concat([winnerscore, winneroldrating], axis=1)
dLesterSchonbrun.corr()

                 winnerscore  winneroldrating
winnerscore         1.000000         0.052294
winneroldrating     0.052294         1.000000

Укажите, верно ли следующее утверждение: характер взаимосвязи (прямая или обратная) между средними значениями переменных winnerscore и winneroldrating для победителя по имени Lester Schonbrun не отличается для такого же показателя для победителя по имени Stuart Goldman. Сгруппируйте датафрейм по переменной tourneyid, затем рассчитайте коэффициент корреляции между средними значениями указанных переменных.

In [66]:
winnerscore = df[df['winnername'] == 'Stuart Goldman'].groupby('tourneyid')['winnerscore'].mean()
winneroldrating = df[df['winnername'] == 'Stuart Goldman'].groupby('tourneyid')['winneroldrating'].mean()
dStuartGoldman = pd.concat([winnerscore, winneroldrating], axis=1)
dStuartGoldman.corr()

                 winnerscore  winneroldrating
winnerscore         1.000000        -0.498531
winneroldrating    -0.498531         1.000000

Выберите данные только за 4376 турнир (переменная tourneyid). Рассчитайте коэффициент корреляции между переменными winnerscore и loserscore. Введите ответ в виде десятичной дроби, округлите до двух знаков после запятой; если связь обратная, не забудьте указать минус перед числом.

In [67]:
df4376 = df[df['tourneyid'] == 4376]
winnerscore = df4376['winnerscore']
loserscore = df4376['loserscore']
scores = pd.concat([winnerscore, loserscore], axis=1)
print(scores)
scores.corr()

       winnerscore  loserscore
17895          397         326
17896          318         315
17897          428         330
17898          366         362
17899          375         342
17900          356         327
17901          462         303
17902          529         286
17903          381         278
17904          516         294
17905          457         317
17906          418         328
17907          461         282
17908          354         309
17909          430         346
17910          430         351
17911          428         396
17912          398         376
17913          443         373
17914          394         391
17915          411         393
17916          403         316

             winnerscore  loserscore
winnerscore     1.000000   -0.249001
loserscore     -0.249001    1.000000